# Generated by Django 3.0.2 on 2020-01-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipestep',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.Recipe'),
            preserve_default=False,
        ),
    ]
