# Generated by Django 3.0.2 on 2020-01-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200105_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='href',
            new_name='link',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
