# Generated by Django 3.0.2 on 2020-01-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200105_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
