# Generated by Django 3.0.2 on 2020-01-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.CharField(default='steps', max_length=50000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeStep',
        ),
    ]
